-- 008_seed_baseline_voice_profile.sql
-- Seeds the default baseline voice profile with modern human corpus data.
-- 29 elements parsed from 316 diverse sources (Wikipedia, news, tech blogs, dev.to).
-- ~432K words total. Generated by Phase 4.5.3 (Session 20).

BEGIN;

-- 1. Ensure baseline profile exists
INSERT INTO voice_profiles (id, name, description, profile_type, is_active)
VALUES (1, 'Baseline', 'Generic modern human voice profile from 316 diverse sources (Wikipedia, news, tech blogs, dev.to). 431,939 total words. 29 elements.', 'baseline', true)
ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description;

-- 2. Clear existing elements for baseline
DELETE FROM profile_elements WHERE voice_profile_id = 1;

-- 3. Insert 29 parsed elements
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'archaic_vocabulary_rate', 'lexical', 'directional', 0.0003, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'automated_readability_index', 'idiosyncratic', 'metric', 0.5703, NULL, 12.2264);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'avg_sentence_length', 'syntactic', 'metric', 0.501, NULL, 21.484);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'avg_word_length', 'lexical', 'metric', 0.485, NULL, 4.8472);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'coleman_liau_index', 'idiosyncratic', 'metric', 0.5515, NULL, 11.0782);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'contraction_rate', 'lexical', 'directional', 0.0, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'ellipsis_usage', 'idiosyncratic', 'directional', 0.0152, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'em_dash_usage', 'idiosyncratic', 'directional', 0.1801, 'more', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'exclamation_rate', 'idiosyncratic', 'directional', 0.0116, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'figurative_language_markers', 'idiosyncratic', 'directional', 0.2057, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'first_person_usage', 'idiosyncratic', 'directional', 0.1408, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'flesch_kincaid_grade', 'idiosyncratic', 'metric', 0.572, NULL, 12.0918);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'flesch_reading_ease', 'idiosyncratic', 'metric', 0.4878, NULL, 46.9378);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'gunning_fog_index', 'idiosyncratic', 'metric', 0.7308, NULL, 15.4287);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'inverted_syntax_rate', 'syntactic', 'directional', 0.1681, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'long_sentence_ratio', 'syntactic', 'directional', 0.2655, 'more', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'long_word_frequency', 'lexical', 'directional', 0.2569, 'more', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'parenthetical_usage', 'idiosyncratic', 'directional', 0.3618, 'more', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'passive_voice_rate', 'syntactic', 'directional', 0.3471, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'rare_word_rate', 'lexical', 'directional', 0.1837, 'more', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'repetition_rate', 'idiosyncratic', 'directional', 0.9466, 'more', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'rhetorical_question_rate', 'idiosyncratic', 'directional', 0.0198, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'second_person_usage', 'idiosyncratic', 'directional', 0.0812, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'semicolon_usage', 'idiosyncratic', 'directional', 0.0935, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'sentence_length_stddev', 'syntactic', 'metric', 0.6306, NULL, 16.2358);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'short_sentence_ratio', 'syntactic', 'directional', 0.2304, 'less', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'smog_index', 'idiosyncratic', 'metric', 0.6705, NULL, 13.7858);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'vocabulary_richness', 'lexical', 'directional', 0.5071, 'more', NULL);
INSERT INTO profile_elements (voice_profile_id, name, category, element_type, weight, direction, target_value) VALUES (1, 'vocative_usage', 'idiosyncratic', 'directional', 0.0987, 'less', NULL);

-- 4. Set active baseline in settings
UPDATE settings SET active_baseline_id = 1 WHERE id = 1 AND EXISTS (SELECT 1 FROM voice_profiles WHERE id = 1);

COMMIT;